version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    assignees:
      - "dependabot"
    reviewers:
      - "tom-hauschke"
    labels:
      - dep/github-actions
  - package-ecosystem: terraform
    directory: "/terraform"
    schedule:
      interval: "daily"
    assignees:
      - "dependabot"
    reviewers:
      - "tom-hauschke"
    labels:
      - dep/terraform
